import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'admin-lte/dist/css/adminlte.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { ReactNode } from 'react';
// import Image from 'next/image';
import ClientProviders from '@/components/common/ClientProviders';
import ClientLayoutWrapper from '@/components/common/ClientLayoutWrapper';
// import Wrapper from "@/components/ui/Wrapper";

export const metadata: Metadata = {
  title: "ARCGATE COMPLIANCE MONITORING",
  description: "Generated by Arcgate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      {/* <body className="sidebar-mini sidebar-collapse sidebar-mini-hover layout-fixed layout-footer-fixed layout-navbar-fixed"> */}
        {/* <Wrapper> */}
          {/* Preloader */}
          {/* <div className="preloader flex-column justify-content-center align-items-center" id="app-preloader">
            <Image 
              className="animation__shake"
              src="/logo-icon.png"
              alt="AdminLTELogo"
              height={60}
              width={60}
            />
          </div> */}

          <ClientProviders>
            <ToastContainer />
            <ClientLayoutWrapper>
              {children}
            </ClientLayoutWrapper>
          </ClientProviders>
        {/* </Wrapper> */}
      </body>
    </html>
  );
}
