import type { Metadata } from "next";
import Script from "next/script";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'admin-lte/dist/css/adminlte.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

// styles for DataTables + Bootstrap 4
import 'datatables.net-bs4/css/dataTables.bootstrap4.min.css';
import 'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css';
import 'datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css';

import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// styles for DataTables + Bootstrap 4
import 'datatables.net-bs4/css/dataTables.bootstrap4.min.css';
import 'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css';
import 'datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css';

import { ReactNode } from 'react';
// import Image from 'next/image';
import ClientProviders from '@/components/common/ClientProviders';
import ClientLayoutWrapper from '@/components/common/ClientLayoutWrapper';
import BodyWrapper from "@/components/common/BodyWrapper";
// import Wrapper from "@/components/ui/Wrapper";

export const metadata: Metadata = {
  title: "ARCGATE COMPLIANCE MONITORING",
  description: "Generated by Arcgate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Select2 CSS */}
        <link
          href="/libs/select2.min.css"
          rel="stylesheet"
        />

        {/* jQuery 3.7.1 first */}
        <Script
          src="/libs/jquery-3.7.1.min.js"
          strategy="beforeInteractive"
        />

        {/* Select2 after jQuery */}
        <Script
          src="/libs/select2.full.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <BodyWrapper>
          <ClientProviders>
            <ToastContainer position="top-right" autoClose={3000} />
            <ClientLayoutWrapper>
              {children}
            </ClientLayoutWrapper>
          </ClientProviders>
      </BodyWrapper>
    </html>
  );
}
